schema: "classroom50/repo-config/v1"
classroom: "insy7314-2026-g1"
assignment: "insy7314-2026-hustlehub-plus-part1"
owner:
  username: "humeramathia"
  id: 123939000
  accepted_at: "2026-08-27T13:02:32Z"
